# Generated by Django 4.2.6 on 2023-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_pricedb_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='categoryname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
