# Generated by Django 4.2.6 on 2023-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_cartdb_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
