# Generated by Django 4.2.6 on 2023-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_cartdb_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='prescription',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='prescrip',
            field=models.ImageField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
