# Generated by Django 4.2.6 on 2023-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_cartdb_prescription_cartdb_prescrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.IntegerField(blank=True, null=True)),
                ('cardhold', models.CharField(blank=True, max_length=100, null=True)),
                ('expmon', models.DateField(blank=True, null=True)),
                ('expy', models.DateField(blank=True, null=True)),
                ('ccvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
