# Generated by Django 4.2.6 on 2023-12-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_paymentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='expmon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdb',
            name='expy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
