# Generated by Django 4.2.6 on 2023-12-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_pdfdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdb',
            name='location',
        ),
    ]
