# Generated by Django 4.2.6 on 2023-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_remove_pdfdb_contact_number_remove_pdfdb_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdb',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
