# Generated by Django 4.2.6 on 2023-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_prodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdb',
            name='categoryimage',
            field=models.ImageField(blank=True, null=True, upload_to='catimage'),
        ),
    ]
