# Generated by Django 4.2.6 on 2023-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_catdb_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='nondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonname', models.CharField(blank=True, max_length=100, null=True)),
                ('nonprice', models.IntegerField(blank=True, null=True)),
                ('nonimage', models.ImageField(blank=True, null=True, upload_to='nonprescribe')),
            ],
        ),
    ]
