# Generated by Django 4.2.6 on 2023-11-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_nondb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nondb',
        ),
    ]
